# -*- coding: utf-8 -*-
"""Taller_RPGManager_Herencia.ipynb.

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uJVRvM-BBch89cpzc8EkU7FRt48A0b6B

SECCION 1
"""

from abc import ABC, abstractmethod

class Personaje(ABC):

    def __init__(self, nombre, nivel, vida_max):
        self.nombre = nombre
        self.nivel = nivel
        self.puntos_vida_max = vida_max
        self.puntos_vida = vida_max  # Comienza con vida al máximo

    # Método concreto: recibir daño
    def recibir_dano(self, dano):
        self.puntos_vida -= dano
        if self.puntos_vida < 0:
            self.puntos_vida = 0  # No puede bajar de 0
        print(f"{self.nombre} recibe {dano} de daño. HP: {self.puntos_vida}/{self.puntos_vida_max}")

    # Método concreto: verificar si está vivo
    def esta_vivo(self):
        return self.puntos_vida > 0

    # Métodos abstractos (las subclases DEBEN implementarlos)
    @abstractmethod
    def atacar(self, objetivo):
        pass

    @abstractmethod
    def get_tipo_personaje(self):
        pass

    # Método __str__ (equivalente a toString de Java)
    def __str__(self):
        return f"[{self.get_tipo_personaje()}] {self.nombre} Nv.{self.nivel} | HP: {self.puntos_vida}/{self.puntos_vida_max}"

"""SECCION 2

"""

class Guerrero(Personaje):

    def __init__(self, nombre, nivel):
        super().__init__(nombre, nivel, 100 + nivel * 10)  # vidaMax = 100 + nivel*10
        self.fuerza = 15 + nivel * 3
        self.defensa = 10 + nivel * 2

    def atacar(self, objetivo):
        print(f"{self.nombre} (Guerrero) golpea con fuerza {self.fuerza}")
        objetivo.recibir_dano(self.fuerza)

    def get_tipo_personaje(self):
        return "Guerrero"

    # Método propio
    def usar_escudo(self):
        print(f"{self.nombre} bloquea con defensa {self.defensa}!")


class Mago(Personaje):

    def __init__(self, nombre, nivel):
        super().__init__(nombre, nivel, 60 + nivel * 5)  # vidaMax = 60 + nivel*5
        self.mana_max = 80 + nivel * 10
        self.mana = self.mana_max

    def atacar(self, objetivo):
        if self.mana >= 20:
            dano = 25 + self.nivel * 5
            print(f"{self.nombre} (Mago) lanza hechizo. Daño: {dano} | Mana: -20")
            objetivo.recibir_dano(dano)
            self.mana -= 20
        else:
            print(f"{self.nombre} (Mago) ¡Mana insuficiente! No puede atacar.")

    def get_tipo_personaje(self):
        return "Mago"

    # Método propio
    def recuperar_mana(self, cantidad):
        self.mana += cantidad
        if self.mana > self.mana_max:
            self.mana = self.mana_max
        print(f"{self.nombre} recupera mana. Mana actual: {self.mana}/{self.mana_max}")


class Arquero(Personaje):

    def __init__(self, nombre, nivel):
        super().__init__(nombre, nivel, 75 + nivel * 7)  # vidaMax = 75 + nivel*7
        self.flechas = 10 + nivel * 2
        self.alcance = 30

    def atacar(self, objetivo):
        if self.flechas > 0:
            dano = 12 + self.nivel * 4
            print(f"{self.nombre} (Arquero) dispara flecha. Daño: {dano} | Flechas restantes: {self.flechas - 1}")
            objetivo.recibir_dano(dano)
            self.flechas -= 1
        else:
            print(f"{self.nombre} (Arquero) ¡Sin flechas! No puede atacar.")

    def get_tipo_personaje(self):
        return "Arquero"

    # Método propio
    def recargar_flechas(self, cantidad):
        self.flechas += cantidad
        print(f"{self.nombre} recarga flechas. Flechas actuales: {self.flechas}")

"""EL SIGUIENTE ES EL DE LA PRUEBA RAPIDA"""

thorin = Guerrero("Thorin", 3)
gandalf = Mago("Gandalf", 5)
legolas = Arquero("Legolas", 4)

print(thorin)
print(gandalf)
print(legolas)

"""SECCION 3

"""

# ===== SECCIÓN 3: POLIMORFISMO - LA BATALLA =====

# Crear 3 héroes
heroes = [
    Guerrero("Thorin", 3),
    Mago("Gandalf", 5),
    Arquero("Legolas", 4)
]

# Crear 1 enemigo
orco = Guerrero("Orco", 1)

print("=== INICIA LA BATALLA ===\n")
print("Héroes:")
for h in heroes:
    print(f"  {h}")
print("Enemigo:")
print(f"  {orco}")
print()

# Bucle de batalla
turno = 1

while orco.esta_vivo():
    print(f"--- Turno {turno} ---")

    for h in heroes:
        if orco.esta_vivo():
            h.atacar(orco)

    turno += 1

# Resultado final
print("\n=== BATALLA TERMINADA ===")
print(f"Duración: {turno - 1} turnos\n")
print("Estado final:")
for h in heroes:
    print(f"  {h}")
print(f"  {orco}")

"""SECCION 4

"""

from abc import ABC, abstractmethod

# ===== INTERFACES (Clases ABC) =====

class Habilidoso(ABC):

    @abstractmethod
    def usar_habilidad_especial(self, objetivo):
        pass

    @abstractmethod
    def get_costo_habilidad(self):
        pass

    @abstractmethod
    def get_nombre_habilidad(self):
        pass


class Equipable(ABC):

    @abstractmethod
    def equipar_item(self, item):
        pass

    @abstractmethod
    def get_item_equipado(self):
        pass


class Sanador(ABC):

    @abstractmethod
    def sanar(self, objetivo):
        pass

    @abstractmethod
    def get_potencia_sanacion(self):
        pass


# ===== CLASES MODIFICADAS =====

class Guerrero(Personaje, Habilidoso, Equipable):

    def __init__(self, nombre, nivel):
        super().__init__(nombre, nivel, 100 + nivel * 10)
        self.fuerza = 15 + nivel * 3
        self.defensa = 10 + nivel * 2
        self.item_equipado = "Sin equipo"
        self.costo_habilidad = 30

    def atacar(self, objetivo):
        print(f"{self.nombre} (Guerrero) golpea con fuerza {self.fuerza}")
        objetivo.recibir_dano(self.fuerza)

    def get_tipo_personaje(self):
        return "Guerrero"

    def usar_escudo(self):
        print(f"{self.nombre} bloquea con defensa {self.defensa}!")

    # ===== INTERFACE HABILIDOSO =====
    def usar_habilidad_especial(self, objetivo):
        print(f"{self.nombre} usa Golpe Devastador! Daño: 50")
        objetivo.recibir_dano(50)

    def get_costo_habilidad(self):
        return self.costo_habilidad

    def get_nombre_habilidad(self):
        return "Golpe Devastador"

    # ===== INTERFACE EQUIPABLE =====
    def equipar_item(self, item):
        self.item_equipado = item
        print(f"{self.nombre} equipa {item}!")

    def get_item_equipado(self):
        return self.item_equipado


class Mago(Personaje, Habilidoso, Sanador):

    def __init__(self, nombre, nivel):
        super().__init__(nombre, nivel, 60 + nivel * 5)
        self.mana_max = 80 + nivel * 10
        self.mana = self.mana_max

    def atacar(self, objetivo):
        if self.mana >= 20:
            dano = 25 + self.nivel * 5
            print(f"{self.nombre} (Mago) lanza hechizo. Daño: {dano} | Mana: -20")
            objetivo.recibir_dano(dano)
            self.mana -= 20
        else:
            print(f"{self.nombre} (Mago) ¡Mana insuficiente! No puede atacar.")

    def get_tipo_personaje(self):
        return "Mago"

    def recuperar_mana(self, cantidad):
        self.mana += cantidad
        if self.mana > self.mana_max:
            self.mana = self.mana_max
        print(f"{self.nombre} recupera mana. Mana actual: {self.mana}/{self.mana_max}")

    # ===== INTERFACE HABILIDOSO =====
    def usar_habilidad_especial(self, objetivo):
        if self.mana >= 20:
            print(f"{self.nombre} lanza Bola de Fuego! Daño: 40 | Mana: -20")
            objetivo.recibir_dano(40)
            self.mana -= 20
        else:
            print(f"{self.nombre} ¡Mana insuficiente para Bola de Fuego!")

    def get_costo_habilidad(self):
        return 20

    def get_nombre_habilidad(self):
        return "Bola de Fuego"

    # ===== INTERFACE SANADOR =====
    def sanar(self, objetivo):
        print(f"{self.nombre} sana a {objetivo.nombre}. HP restaurado: 25")
        objetivo.puntos_vida += 25
        if objetivo.puntos_vida > objetivo.puntos_vida_max:
            objetivo.puntos_vida = objetivo.puntos_vida_max

    def get_potencia_sanacion(self):
        return 25


class Arquero(Personaje, Equipable):

    def __init__(self, nombre, nivel):
        super().__init__(nombre, nivel, 75 + nivel * 7)
        self.flechas = 10 + nivel * 2
        self.alcance = 30
        self.item_equipado = "Arco basico"

    def atacar(self, objetivo):
        if self.flechas > 0:
            dano = 12 + self.nivel * 4
            # Si tiene un arco mejorado, +5 de daño
            if self.item_equipado != "Arco basico":
                dano += 5
                print(f"{self.nombre} (Arquero) dispara flecha con {self.item_equipado}. Daño: {dano} (+5 bonus) | Flechas restantes: {self.flechas - 1}")
            else:
                print(f"{self.nombre} (Arquero) dispara flecha. Daño: {dano} | Flechas restantes: {self.flechas - 1}")
            objetivo.recibir_dano(dano)
            self.flechas -= 1
        else:
            print(f"{self.nombre} (Arquero) ¡Sin flechas! No puede atacar.")

    def get_tipo_personaje(self):
        return "Arquero"

    def recargar_flechas(self, cantidad):
        self.flechas += cantidad
        print(f"{self.nombre} recarga flechas. Flechas actuales: {self.flechas}")

    # ===== INTERFACE EQUIPABLE =====
    def equipar_item(self, item):
        self.item_equipado = item
        print(f"{self.nombre} equipa {item}!")

    def get_item_equipado(self):
        return self.item_equipado

"""SECCION 5

"""

# ============================================================
# SECCIÓN 5 — BATALLA COMPLETA CON HABILIDADES
# ============================================================

# Crear 3 héroes
heroes = [
    Guerrero("Thorin", 3),
    Mago("Gandalf", 5),
    Arquero("Legolas", 4)
]

# Crear 1 enemigo
orco = Guerrero("Orco", 1)

# ===== FASE 1: EQUIPAR =====
print("=== FASE 1: EQUIPAR ===\n")

for h in heroes:
    if isinstance(h, Equipable):
        if isinstance(h, Guerrero):
            h.equipar_item("Espada Legendaria")
        elif isinstance(h, Arquero):
            h.equipar_item("Arco Elfico")

print("\n=== FASE 2: BATALLA POR TURNOS ===\n")

print("Héroes:")
for h in heroes:
    print(f"  {h}")
print("Enemigo:")
print(f"  {orco}")
print()

# ===== FASE 2: BATALLA =====
turno = 1

while orco.esta_vivo():
    print(f"--- Turno {turno} ---")

    # En el turno 2, usar habilidad especial antes de atacar
    if turno == 2:
        print(">> ¡Habilidades especiales activadas!\n")
        for h in heroes:
            if isinstance(h, Habilidoso):
                h.usar_habilidad_especial(orco)
    else:
        # Turnos normales: ataque básico
        for h in heroes:
            if orco.esta_vivo():
                h.atacar(orco)

    turno += 1

print("\n=== BATALLA TERMINADA ===\n")

# ===== FASE 3: SANACIÓN POST-BATALLA =====
print("=== FASE 3: SANACIÓN POST-BATALLA ===\n")

# Buscar al héroe con menos vida
heroe_con_menos_vida = heroes[0]
for h in heroes:
    if h.puntos_vida < heroe_con_menos_vida.puntos_vida:
        heroe_con_menos_vida = h

# Cada héroe que sea Sanador cura al más herido
for h in heroes:
    if isinstance(h, Sanador):
        h.sanar(heroe_con_menos_vida)

# ===== ESTADO FINAL =====
print("\n=== ESTADO FINAL ===\n")
for h in heroes:
    print(f"  {h}")
print(f"  {orco}")